{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "DeleteEmployeeFailMsg"
	},
	"Message": "Failed to delete the employee data - {#ActionResults:DeleteEmployeeSrv/error}",
	"OKCaption": "OK"
}