{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "DeleteCurrEmployeeData"
	},
	"Message": "Are you sure you want to delete?",
	"Title": "Warning!!!",
	"OKCaption": "Ok",
	"CancelCaption": "Cancel"
}