{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "UpdateEmployeeSrv"
	},
	"OnFailure": "/capmdk/Actions/UpdateEmpFailureMsg.action",
	"OnSuccess": "/capmdk/Actions/CloseModalPage_Complete.action",
	"Target": {
		"Service": "/capmdk/Services/com_sap_mdk_cap.service",
		"EntitySet": "Employee",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"id": "{id}",
		"empid": "#Control:FCID/#Value",
		"empname": "#Control:FCName/#Value",
		"street": "#Control:FCStreet/#Value",
		"city": "#Control:FCCity/#Value",
		"state": "#Control:FCState/#Value",
		"zip": "#Control:FCZip/#Value"
	}
}