{
	"_Type": "Action.Type.Message",
	"ActionResult": {
		"_Name": "UpdateEmpFailureMsg"
	},
	"Message": "Failed to update employee details - {#ActionResults:UpdateEmployeeSrv/error}",
	"Title": "Update Employee",
	"OKCaption": "OK"
}